---
framework: jest
postMerge:
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
preMerge:
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
preRun:
  command:
    - yarn
postRun:
  command:
    - node --version
version: 1.0
